/* Rezept- und Zutatendatenbank für den Essensplaner.
 *
 * Zutaten: Name → [Kategorie, Einheit, Allergene, Suchbegriffe, Packung?]
 *   Allergene: g = Gluten, l = Laktose, n = Nüsse, e = Ei
 *   Packung:   [Inhalt in Einheit, Singular, Plural] – für die Einkaufsliste
 *
 * Rezepte: Mengen gelten pro Erwachsenem. Zutat [Name, Menge, optional?].
 *   Optionale Zutaten fallen bei passender Unverträglichkeit/Abneigung weg,
 *   statt das ganze Rezept auszuschließen.
 */

const CATEGORIES = [
  { k: 'obst', label: 'Obst & Gemüse', icon: '🥦' },
  { k: 'brot', label: 'Brot & Backwaren', icon: '🥖' },
  { k: 'kuehl', label: 'Kühlregal & Milchprodukte', icon: '🧀' },
  { k: 'fleisch', label: 'Fleisch & Fisch', icon: '🥩' },
  { k: 'trocken', label: 'Nudeln, Reis & Trockenwaren', icon: '🍝' },
  { k: 'konserven', label: 'Konserven, Gläser & Saucen', icon: '🥫' },
  { k: 'tk', label: 'Tiefkühl', icon: '❄️' },
  { k: 'basis', label: 'Basics & Gewürze', icon: '🧂' },
];

const CUISINES = {
  italienisch: 'Italienisch',
  deutsch: 'Hausmannskost',
  asiatisch: 'Asiatisch',
  indisch: 'Indisch',
  mexikanisch: 'Mexikanisch',
  orientalisch: 'Orientalisch',
  mediterran: 'Mediterran',
  amerikanisch: 'Burger & Co.',
  franzoesisch: 'Französisch',
};

const INGREDIENTS = {
  // Obst & Gemüse
  'Zwiebel': ['obst', 'Stk', '', 'zwiebeln'],
  'Knoblauch': ['obst', 'Zehe', '', 'knoblauchzehe'],
  'Karotte': ['obst', 'Stk', '', 'karotten möhre möhren'],
  'Paprika': ['obst', 'Stk', '', 'paprikaschote'],
  'Zucchini': ['obst', 'Stk', '', ''],
  'Champignons': ['obst', 'g', '', 'pilze champignon'],
  'Brokkoli': ['obst', 'g', '', 'broccoli'],
  'Kartoffeln': ['obst', 'g', '', 'kartoffel'],
  'Süßkartoffel': ['obst', 'g', '', 'süßkartoffeln'],
  'Lauch': ['obst', 'Stk', '', 'porree'],
  'Ingwer': ['obst', 'g', '', ''],
  'Frühlingszwiebeln': ['obst', 'Bund', '', 'lauchzwiebeln'],
  'Kirschtomaten': ['obst', 'g', '', 'tomate tomaten cherrytomaten'],
  'Tomaten': ['obst', 'Stk', '', 'tomate'],
  'Gurke': ['obst', 'Stk', '', 'gurken salatgurke'],
  'Romanasalat': ['obst', 'Stk', '', 'salat'],
  'Babyspinat': ['obst', 'g', '', 'spinat'],
  'Hokkaido-Kürbis': ['obst', 'g', '', 'kürbis'],
  'Avocado': ['obst', 'Stk', '', 'avocados'],
  'Zitrone': ['obst', 'Stk', '', 'zitronen'],
  'Limette': ['obst', 'Stk', '', 'limetten'],
  'Banane': ['obst', 'Stk', '', 'bananen'],
  'Apfel': ['obst', 'Stk', '', 'äpfel'],
  'Pak Choi': ['obst', 'Stk', '', 'pak-choi'],
  'Basilikum': ['obst', 'Bund', '', 'kräuter'],
  'Petersilie': ['obst', 'Bund', '', 'kräuter'],
  'Schnittlauch': ['obst', 'Bund', '', 'kräuter'],

  // Brot & Backwaren
  'Baguette': ['brot', 'Stk', 'g', 'brot'],
  'Toastbrot': ['brot', 'Scheibe', 'g', 'toast brot'],
  'Vollkornbrot': ['brot', 'Scheibe', 'g', 'brot'],
  'Brötchen': ['brot', 'Stk', 'g', 'semmel'],
  'Burgerbrötchen': ['brot', 'Stk', 'g', 'brötchen buns'],
  'Tortilla-Wraps': ['brot', 'Stk', 'g', 'wraps tortillas', [8, 'Packung', 'Packungen']],

  // Kühlregal
  'Milch': ['kuehl', 'ml', 'l', '', [1000, 'Liter', 'Liter']],
  'Haferdrink': ['kuehl', 'ml', 'g', 'hafermilch', [1000, 'Liter', 'Liter']],
  'Butter': ['kuehl', 'g', 'l', '', [250, 'Stück', 'Stück']],
  'Sahne': ['kuehl', 'ml', 'l', 'schlagsahne', [200, 'Becher', 'Becher']],
  'Saure Sahne': ['kuehl', 'g', 'l', 'sahne', [200, 'Becher', 'Becher']],
  'Schmand': ['kuehl', 'g', 'l', 'sahne', [200, 'Becher', 'Becher']],
  'Frischkäse': ['kuehl', 'g', 'l', 'käse', [175, 'Packung', 'Packungen']],
  'Quark': ['kuehl', 'g', 'l', 'magerquark', [500, 'Becher', 'Becher']],
  'Naturjoghurt': ['kuehl', 'g', 'l', 'joghurt', [500, 'Becher', 'Becher']],
  'Parmesan': ['kuehl', 'g', 'l', 'käse'],
  'Geriebener Käse': ['kuehl', 'g', 'l', 'käse gouda emmentaler', [200, 'Beutel', 'Beutel']],
  'Käse in Scheiben': ['kuehl', 'g', 'l', 'käse gouda', [150, 'Packung', 'Packungen']],
  'Mozzarella': ['kuehl', 'g', 'l', 'käse', [125, 'Kugel', 'Kugeln']],
  'Feta': ['kuehl', 'g', 'l', 'käse schafskäse', [200, 'Packung', 'Packungen']],
  'Halloumi': ['kuehl', 'g', 'l', 'käse grillkäse', [225, 'Packung', 'Packungen']],
  'Eier': ['kuehl', 'Stk', 'e', 'ei'],
  'Tofu': ['kuehl', 'g', '', 'soja', [200, 'Packung', 'Packungen']],
  'Hummus': ['kuehl', 'g', '', 'kichererbsen', [200, 'Becher', 'Becher']],
  'Falafel': ['kuehl', 'g', '', 'kichererbsen', [200, 'Packung', 'Packungen']],
  'Spätzle': ['kuehl', 'g', 'g e', 'nudeln', [500, 'Packung', 'Packungen']],
  'Gnocchi': ['kuehl', 'g', 'g', '', [500, 'Packung', 'Packungen']],
  'Flammkuchenteig': ['kuehl', 'Rolle', 'g', 'teig'],
  'Quicheteig': ['kuehl', 'Rolle', 'g l', 'mürbeteig teig'],

  // Fleisch & Fisch
  'Rinderhackfleisch': ['fleisch', 'g', '', 'hack hackfleisch rind fleisch'],
  'Hackfleisch gemischt': ['fleisch', 'g', '', 'hack hackfleisch schwein rind fleisch'],
  'Hähnchenbrust': ['fleisch', 'g', '', 'hähnchen huhn geflügel fleisch'],
  'Schweineschnitzel': ['fleisch', 'g', '', 'schwein schnitzel fleisch'],
  'Rindergulasch': ['fleisch', 'g', '', 'rind gulasch fleisch'],
  'Hüftsteak': ['fleisch', 'g', '', 'rind steak fleisch'],
  'Wiener Würstchen': ['fleisch', 'Stk', '', 'wurst würstchen schwein fleisch'],
  'Speckwürfel': ['fleisch', 'g', '', 'speck schwein fleisch', [125, 'Packung', 'Packungen']],
  'Lachsfilet': ['fleisch', 'g', '', 'lachs fisch'],

  // Trockenwaren
  'Spaghetti': ['trocken', 'g', 'g', 'nudeln pasta', [500, 'Packung', 'Packungen']],
  'Penne': ['trocken', 'g', 'g', 'nudeln pasta', [500, 'Packung', 'Packungen']],
  'Bandnudeln': ['trocken', 'g', 'g e', 'nudeln pasta tagliatelle', [500, 'Packung', 'Packungen']],
  'Lasagneplatten': ['trocken', 'g', 'g', 'nudeln pasta', [250, 'Packung', 'Packungen']],
  'Mie-Nudeln': ['trocken', 'g', 'g', 'nudeln', [250, 'Packung', 'Packungen']],
  'Reis': ['trocken', 'g', '', 'basmati'],
  'Risottoreis': ['trocken', 'g', '', 'reis', [500, 'Packung', 'Packungen']],
  'Rote Linsen': ['trocken', 'g', '', 'linsen hülsenfrüchte', [500, 'Packung', 'Packungen']],
  'Tellerlinsen': ['trocken', 'g', '', 'linsen hülsenfrüchte', [500, 'Packung', 'Packungen']],
  'Couscous': ['trocken', 'g', 'g', '', [500, 'Packung', 'Packungen']],
  'Bulgur': ['trocken', 'g', 'g', '', [500, 'Packung', 'Packungen']],
  'Mehl': ['trocken', 'g', 'g', ''],
  'Paniermehl': ['trocken', 'g', 'g', 'semmelbrösel'],
  'Haferflocken': ['trocken', 'g', 'g', 'hafer', [500, 'Packung', 'Packungen']],
  'Müsli': ['trocken', 'g', 'g n', '', [750, 'Packung', 'Packungen']],
  'Trockenhefe': ['trocken', 'Pck', '', 'hefe'],
  'Walnüsse': ['trocken', 'g', 'n', 'nüsse nuss', [200, 'Beutel', 'Beutel']],

  // Konserven & Saucen
  'Gehackte Tomaten': ['konserven', 'g', '', 'tomaten tomate', [400, 'Dose', 'Dosen']],
  'Passierte Tomaten': ['konserven', 'ml', '', 'tomaten tomate', [500, 'Packung', 'Packungen']],
  'Tomatenmark': ['konserven', 'EL', '', 'tomaten'],
  'Kokosmilch': ['konserven', 'ml', '', 'kokos', [400, 'Dose', 'Dosen']],
  'Kidneybohnen': ['konserven', 'g', '', 'bohnen hülsenfrüchte', [250, 'Dose', 'Dosen']],
  'Mais': ['konserven', 'g', '', '', [140, 'Dose', 'Dosen']],
  'Kichererbsen': ['konserven', 'g', '', 'hülsenfrüchte', [240, 'Dose', 'Dosen']],
  'Oliven': ['konserven', 'g', '', '', [160, 'Glas', 'Gläser']],
  'Apfelmus': ['konserven', 'g', '', 'apfel', [700, 'Glas', 'Gläser']],
  'Rote Currypaste': ['konserven', 'TL', '', 'curry'],
  'Teriyakisauce': ['konserven', 'EL', 'g', 'soja'],
  'Pesto': ['konserven', 'g', 'l n', 'basilikum', [190, 'Glas', 'Gläser']],
  'Marmelade': ['konserven', 'g', '', 'konfitüre', [450, 'Glas', 'Gläser']],

  // Tiefkühl
  'Erbsen (TK)': ['tk', 'g', '', 'erbsen', [450, 'Beutel', 'Beutel']],
  'Fischstäbchen': ['tk', 'Stk', 'g', 'fisch', [15, 'Packung', 'Packungen']],
  'Beeren (TK)': ['tk', 'g', '', 'beeren', [300, 'Beutel', 'Beutel']],
  'Seelachsfilet': ['tk', 'g', '', 'fisch seelachs', [400, 'Packung', 'Packungen']],

  // Basics (meist vorhanden)
  'Salz': ['basis', '', '', ''],
  'Pfeffer': ['basis', '', '', ''],
  'Olivenöl': ['basis', 'EL', '', 'öl'],
  'Rapsöl': ['basis', 'EL', '', 'öl'],
  'Gemüsebrühe': ['basis', 'ml', '', 'brühe'],
  'Zucker': ['basis', 'TL', '', ''],
  'Backpulver': ['basis', 'TL', '', ''],
  'Speisestärke': ['basis', 'TL', '', 'stärke'],
  'Currypulver': ['basis', 'TL', '', 'curry'],
  'Paprikapulver': ['basis', 'TL', '', ''],
  'Kreuzkümmel': ['basis', 'TL', '', 'cumin'],
  'Oregano': ['basis', 'TL', '', ''],
  'Zimt': ['basis', 'TL', '', ''],
  'Kräuter der Provence': ['basis', 'TL', '', ''],
  'Majoran': ['basis', 'TL', '', ''],
  'Chiliflocken': ['basis', 'TL', '', 'chili scharf'],
  'Muskat': ['basis', '', '', 'muskatnuss'],
  'Sojasauce': ['basis', 'EL', 'g', 'soja'],
  'Senf': ['basis', 'TL', '', ''],
  'Essig': ['basis', 'EL', '', ''],
  'Honig': ['basis', 'TL', '', ''],
  'Ahornsirup': ['basis', 'EL', '', ''],
  'Sesam': ['basis', 'TL', '', ''],
  'Ketchup': ['basis', 'EL', '', ''],
};

function M(id, n, e, meta, i, s) { return { id, n, e, m: 'main', ...meta, i, s }; }
function B(id, n, e, meta, i, s) { return { id, n, e, m: 'fruehstueck', p: 'fruehstueck', k: '', rest: 0, ...meta, i, s }; }

// d: vegan | veggie | fisch | fleisch · p: Hauptzutat (für Abwechslung) · k: Küche
// t: Minuten · c: Kosten 1–3 · kid: kinderfreundlich · rest: eignet sich zum Vorkochen/Reste
const RECIPES = [
  M('bolo', 'Spaghetti Bolognese', '🍝', { d: 'fleisch', p: 'rind', k: 'italienisch', t: 40, c: 2, kid: 1, rest: 1 },
    [['Spaghetti', 125], ['Rinderhackfleisch', 125], ['Zwiebel', 0.5], ['Knoblauch', 1], ['Karotte', 0.5], ['Passierte Tomaten', 200], ['Tomatenmark', 1], ['Parmesan', 15, 1], ['Olivenöl', 1], ['Oregano', 0.5]],
    ['Zwiebel, Knoblauch und Karotte fein würfeln.', 'Hackfleisch in Olivenöl krümelig anbraten, Gemüse kurz mitbraten, Tomatenmark mitrösten.', 'Passierte Tomaten und Oregano zugeben, salzen, pfeffern und mindestens 20 Min. leise köcheln lassen.', 'Spaghetti nach Packungsangabe kochen und mit der Sauce und Parmesan servieren.']),
  M('pomodoro', 'Pasta Pomodoro', '🍅', { d: 'veggie', p: 'gemuese', k: 'italienisch', t: 20, c: 1, kid: 1, rest: 0 },
    [['Spaghetti', 125], ['Gehackte Tomaten', 200], ['Knoblauch', 1], ['Basilikum', 0.25], ['Parmesan', 15, 1], ['Olivenöl', 1], ['Zucker', 0.25]],
    ['Knoblauch in Scheiben in Olivenöl sanft anschwitzen.', 'Tomaten und eine Prise Zucker zugeben, 10 Min. köcheln, mit Salz und Pfeffer abschmecken.', 'Spaghetti kochen, mit der Sauce mischen, Basilikum zupfen und mit Parmesan servieren.']),
  M('lasagne', 'Gemüse-Lasagne', '🥘', { d: 'veggie', p: 'gemuese', k: 'italienisch', t: 70, c: 2, kid: 1, rest: 1 },
    [['Lasagneplatten', 80], ['Zucchini', 0.5], ['Paprika', 0.5], ['Zwiebel', 0.5], ['Passierte Tomaten', 150], ['Milch', 150], ['Butter', 15], ['Mehl', 15], ['Geriebener Käse', 40], ['Olivenöl', 1], ['Oregano', 0.5], ['Muskat', 0]],
    ['Gemüse würfeln, in Öl anbraten, Tomaten und Oregano zugeben und 10 Min. köcheln.', 'Für die Béchamel Butter schmelzen, Mehl anschwitzen, Milch einrühren, aufkochen und mit Salz und Muskat würzen.', 'Abwechselnd Platten, Gemüsesauce und Béchamel in eine Form schichten, mit Käse bestreuen.', 'Bei 180 °C Umluft ca. 35 Min. backen.']),
  M('risotto', 'Pilzrisotto', '🍄', { d: 'veggie', p: 'kaese', k: 'italienisch', t: 40, c: 2, kid: 0, rest: 0 },
    [['Risottoreis', 90], ['Champignons', 150], ['Zwiebel', 0.5], ['Knoblauch', 1], ['Gemüsebrühe', 300], ['Parmesan', 20], ['Butter', 10], ['Olivenöl', 1], ['Petersilie', 0.15]],
    ['Pilze in Scheiben schneiden und in Öl kräftig anbraten, beiseitestellen.', 'Zwiebel und Knoblauch in Butter anschwitzen, Reis zugeben und glasig dünsten.', 'Nach und nach heiße Brühe angießen und unter Rühren ca. 18–20 Min. garen.', 'Pilze, Parmesan und gehackte Petersilie unterheben, abschmecken.']),
  M('pizza', 'Pizza Margherita (selbstgemacht)', '🍕', { d: 'veggie', p: 'kaese', k: 'italienisch', t: 45, c: 1, kid: 1, rest: 0 },
    [['Mehl', 125], ['Trockenhefe', 0.25], ['Olivenöl', 1], ['Passierte Tomaten', 80], ['Mozzarella', 70], ['Basilikum', 0.15], ['Oregano', 0.25]],
    ['Mehl, Hefe, Salz, Öl und ca. 75 ml lauwarmes Wasser pro Person zu einem glatten Teig kneten, 30 Min. gehen lassen.', 'Ofen auf 250 °C Ober-/Unterhitze vorheizen.', 'Teig dünn ausrollen, mit gewürzten Tomaten bestreichen und Mozzarella darauf zupfen.', '10–12 Min. backen und mit Basilikum belegen.']),
  M('minestrone', 'Minestrone', '🥣', { d: 'vegan', p: 'gemuese', k: 'italienisch', t: 40, c: 1, kid: 1, rest: 1 },
    [['Zucchini', 0.33], ['Karotte', 0.5], ['Lauch', 0.25], ['Kartoffeln', 100], ['Gehackte Tomaten', 100], ['Kidneybohnen', 60], ['Gemüsebrühe', 350], ['Penne', 30], ['Olivenöl', 1], ['Basilikum', 0.1]],
    ['Gemüse und Kartoffeln klein würfeln und in Olivenöl anschwitzen.', 'Tomaten und Brühe zugeben, 15 Min. köcheln.', 'Nudeln und Bohnen zugeben und weitere 10 Min. garen.', 'Mit Salz, Pfeffer und Basilikum abschmecken.']),
  M('curry', 'Hähnchen-Curry mit Reis', '🍛', { d: 'fleisch', p: 'huhn', k: 'indisch', t: 35, c: 2, kid: 1, rest: 1 },
    [['Hähnchenbrust', 150], ['Kokosmilch', 100], ['Zwiebel', 0.5], ['Paprika', 0.5], ['Erbsen (TK)', 50], ['Ingwer', 5], ['Currypulver', 1], ['Reis', 75], ['Rapsöl', 1]],
    ['Reis nach Packungsangabe kochen.', 'Hähnchen würfeln und in Öl rundum anbraten.', 'Zwiebel, Paprika und Ingwer zugeben, Currypulver kurz mitrösten.', 'Kokosmilch und Erbsen zugeben, 10 Min. köcheln und abschmecken.']),
  M('dal', 'Rotes Linsen-Dal', '🥣', { d: 'vegan', p: 'huelsen', k: 'indisch', t: 30, c: 1, kid: 1, rest: 1 },
    [['Rote Linsen', 80], ['Kokosmilch', 100], ['Gehackte Tomaten', 100], ['Zwiebel', 0.5], ['Knoblauch', 1], ['Ingwer', 5], ['Currypulver', 1], ['Kreuzkümmel', 0.5], ['Reis', 60], ['Rapsöl', 1], ['Zitrone', 0.25]],
    ['Zwiebel, Knoblauch und Ingwer in Öl anschwitzen, Gewürze kurz mitrösten.', 'Linsen, Tomaten, Kokosmilch und ca. 150 ml Wasser pro Person zugeben und 15–20 Min. sämig köcheln.', 'Währenddessen Reis kochen.', 'Mit Salz und Zitronensaft abschmecken.']),
  M('kichercurry', 'Kichererbsen-Spinat-Curry', '🍛', { d: 'vegan', p: 'huelsen', k: 'indisch', t: 25, c: 1, kid: 0, rest: 1 },
    [['Kichererbsen', 130], ['Babyspinat', 75], ['Gehackte Tomaten', 150], ['Kokosmilch', 80], ['Zwiebel', 0.5], ['Knoblauch', 1], ['Ingwer', 5], ['Currypulver', 1], ['Reis', 70], ['Rapsöl', 1]],
    ['Reis kochen.', 'Zwiebel, Knoblauch und Ingwer in Öl anbraten, Currypulver kurz mitrösten.', 'Kichererbsen, Tomaten und Kokosmilch zugeben, 10 Min. köcheln.', 'Spinat unterheben, zusammenfallen lassen und abschmecken.']),
  M('bami', 'Gebratene Nudeln mit Gemüse', '🥢', { d: 'vegan', p: 'gemuese', k: 'asiatisch', t: 25, c: 1, kid: 1, rest: 0 },
    [['Mie-Nudeln', 100], ['Karotte', 0.5], ['Paprika', 0.5], ['Pak Choi', 0.5], ['Frühlingszwiebeln', 0.25], ['Ingwer', 5], ['Knoblauch', 1], ['Sojasauce', 2], ['Rapsöl', 1], ['Sesam', 0.5, 1]],
    ['Nudeln nach Packungsangabe garen und kalt abschrecken.', 'Gemüse in feine Streifen schneiden und im heißen Öl im Wok 3–4 Min. braten.', 'Ingwer, Knoblauch, Nudeln und Sojasauce zugeben und kurz mitbraten.', 'Mit Frühlingszwiebeln und Sesam bestreuen.']),
  M('tofu', 'Knusper-Tofu mit Brokkoli & Reis', '🥦', { d: 'vegan', p: 'tofu', k: 'asiatisch', t: 30, c: 2, kid: 0, rest: 0 },
    [['Tofu', 125], ['Brokkoli', 150], ['Reis', 75], ['Sojasauce', 2], ['Speisestärke', 1], ['Ingwer', 5], ['Knoblauch', 1], ['Rapsöl', 1.5], ['Ahornsirup', 0.5], ['Sesam', 0.5, 1]],
    ['Reis kochen.', 'Tofu trocken tupfen, würfeln, in Stärke wenden und in Öl rundum knusprig braten.', 'Brokkoli in Röschen 4 Min. blanchieren.', 'Sojasauce, Ahornsirup, Ingwer und Knoblauch verrühren, mit Tofu und Brokkoli in der Pfanne schwenken, mit Sesam servieren.']),
  M('thaicurry', 'Thai-Gemüsecurry', '🥥', { d: 'vegan', p: 'gemuese', k: 'asiatisch', t: 30, c: 2, kid: 0, rest: 1 },
    [['Kokosmilch', 150], ['Rote Currypaste', 1], ['Süßkartoffel', 100], ['Paprika', 0.5], ['Brokkoli', 100], ['Reis', 75], ['Limette', 0.25], ['Sojasauce', 1], ['Rapsöl', 0.5]],
    ['Reis kochen.', 'Currypaste (auf „ohne Garnelen“ achten) in Öl kurz anrösten, Kokosmilch angießen.', 'Süßkartoffel würfeln und 8 Min. darin köcheln, dann Paprika und Brokkoli 5 Min. mitgaren.', 'Mit Sojasauce und Limettensaft abschmecken.']),
  M('teriyaki', 'Teriyaki-Lachs mit Reis & Gurke', '🍣', { d: 'fisch', p: 'fisch', k: 'asiatisch', t: 25, c: 3, kid: 1, rest: 0 },
    [['Lachsfilet', 125], ['Reis', 75], ['Gurke', 0.33], ['Teriyakisauce', 2], ['Frühlingszwiebeln', 0.15], ['Essig', 0.5], ['Rapsöl', 0.5], ['Sesam', 0.5, 1]],
    ['Reis kochen.', 'Gurke in dünne Scheiben schneiden und mit Essig und einer Prise Salz marinieren.', 'Lachs in Öl 3 Min. pro Seite braten, Teriyakisauce zugeben und glasieren.', 'Mit Reis, Gurke, Frühlingszwiebeln und Sesam anrichten.']),
  M('rindbrok', 'Rindfleisch-Brokkoli-Pfanne', '🥩', { d: 'fleisch', p: 'rind', k: 'asiatisch', t: 25, c: 3, kid: 0, rest: 0 },
    [['Hüftsteak', 125], ['Brokkoli', 150], ['Reis', 75], ['Sojasauce', 2], ['Ingwer', 5], ['Knoblauch', 1], ['Speisestärke', 1], ['Honig', 0.5], ['Rapsöl', 1]],
    ['Reis kochen.', 'Fleisch in dünne Streifen schneiden, mit Stärke und 1 EL Sojasauce mischen.', 'Brokkoli 3 Min. blanchieren.', 'Fleisch im sehr heißen Öl scharf anbraten, Brokkoli, Ingwer, Knoblauch, restliche Sojasauce und Honig zugeben und kurz schwenken.']),
  M('nudelsuppe', 'Asia-Nudelsuppe mit Hähnchen', '🍜', { d: 'fleisch', p: 'huhn', k: 'asiatisch', t: 30, c: 2, kid: 1, rest: 0 },
    [['Hähnchenbrust', 100], ['Mie-Nudeln', 60], ['Gemüsebrühe', 400], ['Pak Choi', 0.5], ['Karotte', 0.5], ['Champignons', 50], ['Frühlingszwiebeln', 0.15], ['Ingwer', 5], ['Sojasauce', 1.5], ['Limette', 0.25]],
    ['Brühe mit Ingwer aufkochen.', 'Hähnchen in dünne Streifen, Gemüse und Pilze klein schneiden, 8 Min. in der Brühe garen.', 'Nudeln zugeben und nach Packungsangabe ziehen lassen.', 'Mit Sojasauce und Limette abschmecken, mit Frühlingszwiebeln servieren.']),
  M('chili', 'Chili con Carne', '🌶️', { d: 'fleisch', p: 'rind', k: 'mexikanisch', t: 45, c: 2, kid: 0, rest: 1 },
    [['Rinderhackfleisch', 100], ['Kidneybohnen', 120], ['Mais', 60], ['Gehackte Tomaten', 200], ['Zwiebel', 0.5], ['Knoblauch', 1], ['Paprika', 0.5], ['Tomatenmark', 1], ['Paprikapulver', 1], ['Kreuzkümmel', 0.5], ['Chiliflocken', 0.25], ['Reis', 60], ['Rapsöl', 1]],
    ['Hackfleisch in Öl krümelig anbraten, Zwiebel, Knoblauch und Paprika mitbraten.', 'Tomatenmark und Gewürze kurz mitrösten.', 'Tomaten, Bohnen und Mais zugeben und 25 Min. köcheln lassen.', 'Mit Reis servieren.']),
  M('chilisin', 'Chili sin Carne mit Süßkartoffel', '🌶️', { d: 'vegan', p: 'huelsen', k: 'mexikanisch', t: 40, c: 1, kid: 0, rest: 1 },
    [['Süßkartoffel', 150], ['Kidneybohnen', 120], ['Mais', 60], ['Gehackte Tomaten', 200], ['Zwiebel', 0.5], ['Knoblauch', 1], ['Paprika', 0.5], ['Tomatenmark', 1], ['Paprikapulver', 1], ['Kreuzkümmel', 0.5], ['Chiliflocken', 0.25], ['Reis', 60], ['Rapsöl', 1]],
    ['Zwiebel, Knoblauch und Paprika in Öl anbraten, Tomatenmark und Gewürze mitrösten.', 'Süßkartoffel würfeln und mit Tomaten und etwas Wasser zugeben, 15 Min. köcheln.', 'Bohnen und Mais zugeben, weitere 10 Min. garen.', 'Mit Reis servieren.']),
  M('wraps', 'Bohnen-Wraps mit Käse', '🌯', { d: 'veggie', p: 'huelsen', k: 'mexikanisch', t: 25, c: 1, kid: 1, rest: 0 },
    [['Tortilla-Wraps', 2], ['Kidneybohnen', 100], ['Mais', 50], ['Paprika', 0.5], ['Geriebener Käse', 30], ['Saure Sahne', 40], ['Romanasalat', 0.25], ['Tomaten', 1], ['Paprikapulver', 0.5], ['Kreuzkümmel', 0.25]],
    ['Bohnen abspülen, mit Mais, gewürfelter Paprika und Gewürzen 5 Min. in der Pfanne erhitzen und leicht zerdrücken.', 'Salat und Tomaten schneiden.', 'Wraps kurz erwärmen, mit Bohnenmasse, Käse, Salat, Tomaten und saurer Sahne füllen und einrollen.']),
  M('fajitas', 'Chicken Fajitas', '🌮', { d: 'fleisch', p: 'huhn', k: 'mexikanisch', t: 30, c: 2, kid: 1, rest: 0 },
    [['Hähnchenbrust', 130], ['Paprika', 1], ['Zwiebel', 0.5], ['Tortilla-Wraps', 2], ['Saure Sahne', 40], ['Limette', 0.25], ['Paprikapulver', 1], ['Kreuzkümmel', 0.5], ['Rapsöl', 1]],
    ['Hähnchen in Streifen schneiden, mit Gewürzen, Öl und Limettensaft marinieren.', 'Paprika und Zwiebel in Streifen schneiden.', 'Fleisch scharf anbraten, Gemüse zugeben und 5 Min. mitbraten.', 'In warmen Wraps mit saurer Sahne servieren.']),
  M('ofenfeta', 'Ofengemüse mit Feta', '🫑', { d: 'veggie', p: 'kaese', k: 'mediterran', t: 40, c: 1, kid: 0, rest: 0 },
    [['Kartoffeln', 200], ['Zucchini', 0.5], ['Paprika', 0.5], ['Zwiebel', 0.5], ['Feta', 75], ['Olivenöl', 1.5], ['Kräuter der Provence', 1]],
    ['Ofen auf 200 °C Umluft vorheizen.', 'Kartoffeln in Spalten, Gemüse in grobe Stücke schneiden und mit Öl, Kräutern, Salz und Pfeffer mischen.', 'Ca. 25 Min. backen, Feta darüberbröseln und weitere 10 Min. backen.']),
  M('blech', 'Hähnchen-Ofengemüse vom Blech', '🍗', { d: 'fleisch', p: 'huhn', k: 'mediterran', t: 45, c: 2, kid: 1, rest: 0 },
    [['Hähnchenbrust', 150], ['Kartoffeln', 200], ['Paprika', 0.5], ['Zucchini', 0.5], ['Zwiebel', 0.5], ['Knoblauch', 1], ['Olivenöl', 1.5], ['Paprikapulver', 1], ['Kräuter der Provence', 0.5]],
    ['Ofen auf 200 °C Umluft vorheizen.', 'Kartoffeln in Spalten schneiden, mit Öl und Gewürzen mischen und 15 Min. vorbacken.', 'Hähnchen und Gemüse in Stücke schneiden, würzen, aufs Blech geben.', 'Alles weitere 20–25 Min. backen, bis das Hähnchen durch ist.']),
  M('fetapasta', 'Ofen-Feta-Pasta', '🧀', { d: 'veggie', p: 'kaese', k: 'mediterran', t: 30, c: 2, kid: 1, rest: 0 },
    [['Penne', 110], ['Feta', 60], ['Kirschtomaten', 150], ['Knoblauch', 1], ['Olivenöl', 1.5], ['Basilikum', 0.15], ['Chiliflocken', 0.1, 1]],
    ['Ofen auf 200 °C vorheizen.', 'Tomaten und Knoblauch in eine Form geben, Feta in die Mitte, mit Öl beträufeln und würzen. 25 Min. backen.', 'Währenddessen Nudeln kochen.', 'Feta und Tomaten zerdrücken, mit den Nudeln vermengen und mit Basilikum servieren.']),
  M('bauernsalat', 'Griechischer Bauernsalat mit Baguette', '🥗', { d: 'veggie', p: 'kaese', k: 'mediterran', t: 15, c: 2, kid: 0, rest: 0 },
    [['Gurke', 0.5], ['Tomaten', 2], ['Paprika', 0.5], ['Feta', 75], ['Oliven', 30], ['Zwiebel', 0.25], ['Olivenöl', 1.5], ['Essig', 0.5], ['Oregano', 0.25], ['Baguette', 0.33, 1]],
    ['Gurke, Tomaten und Paprika grob würfeln, Zwiebel in Ringe schneiden.', 'Mit Oliven, Öl, Essig, Oregano, Salz und Pfeffer mischen.', 'Feta in Würfeln darauf geben und mit Baguette servieren.']),
  M('seelachs', 'Seelachs in Tomaten-Paprika-Sauce mit Reis', '🐟', { d: 'fisch', p: 'fisch', k: 'mediterran', t: 30, c: 2, kid: 1, rest: 0 },
    [['Seelachsfilet', 130], ['Gehackte Tomaten', 150], ['Paprika', 0.5], ['Zwiebel', 0.5], ['Knoblauch', 1], ['Reis', 70], ['Olivenöl', 1], ['Oregano', 0.25], ['Zitrone', 0.25]],
    ['Reis kochen.', 'Zwiebel, Knoblauch und Paprika in Öl anbraten, Tomaten und Oregano zugeben, 5 Min. köcheln.', 'Fisch salzen, mit Zitrone beträufeln, in die Sauce legen und zugedeckt 10 Min. garziehen lassen.']),
  M('shakshuka', 'Shakshuka mit Baguette', '🍳', { d: 'veggie', p: 'ei', k: 'orientalisch', t: 25, c: 1, kid: 0, rest: 0 },
    [['Eier', 2], ['Gehackte Tomaten', 200], ['Paprika', 0.5], ['Zwiebel', 0.5], ['Knoblauch', 1], ['Kreuzkümmel', 0.5], ['Paprikapulver', 0.5], ['Feta', 30, 1], ['Petersilie', 0.15], ['Baguette', 0.33, 1], ['Olivenöl', 1]],
    ['Zwiebel, Knoblauch und Paprika in Öl weich dünsten, Gewürze kurz mitrösten.', 'Tomaten zugeben und 10 Min. einköcheln.', 'Mulden in die Sauce drücken, Eier hineinschlagen und zugedeckt 6–8 Min. stocken lassen.', 'Mit Feta und Petersilie bestreuen und mit Baguette servieren.']),
  M('falafel', 'Falafel-Bowl mit Hummus', '🧆', { d: 'vegan', p: 'huelsen', k: 'orientalisch', t: 25, c: 2, kid: 0, rest: 0 },
    [['Falafel', 150], ['Hummus', 60], ['Bulgur', 60], ['Gurke', 0.25], ['Tomaten', 1], ['Romanasalat', 0.25], ['Zitrone', 0.25], ['Olivenöl', 1], ['Petersilie', 0.15]],
    ['Bulgur mit der 1,5-fachen Menge kochendem Salzwasser übergießen und 10 Min. quellen lassen.', 'Falafel nach Packungsangabe im Ofen oder in der Pfanne erhitzen.', 'Gemüse schneiden und mit Zitrone, Öl und Salz anmachen.', 'Bowls mit Bulgur, Salat, Falafel, Hummus und Petersilie anrichten.']),
  M('couscous', 'Couscous-Salat mit Kichererbsen', '🥗', { d: 'vegan', p: 'huelsen', k: 'orientalisch', t: 20, c: 1, kid: 0, rest: 1 },
    [['Couscous', 70], ['Kichererbsen', 100], ['Gurke', 0.25], ['Tomaten', 1], ['Paprika', 0.25], ['Petersilie', 0.25], ['Zitrone', 0.5], ['Olivenöl', 1.5], ['Kreuzkümmel', 0.25]],
    ['Couscous mit gleicher Menge kochendem Salzwasser übergießen, 5 Min. quellen lassen, auflockern.', 'Gemüse würfeln, Petersilie hacken, Kichererbsen abspülen.', 'Alles mit Zitronensaft, Öl, Kreuzkümmel, Salz und Pfeffer mischen. Schmeckt auch am nächsten Tag.']),
  M('suesskart', 'Ofen-Süßkartoffel mit Kichererbsen & Hummus', '🍠', { d: 'vegan', p: 'huelsen', k: 'orientalisch', t: 40, c: 2, kid: 0, rest: 0 },
    [['Süßkartoffel', 300], ['Kichererbsen', 100], ['Hummus', 50], ['Babyspinat', 30], ['Zitrone', 0.25], ['Olivenöl', 1], ['Paprikapulver', 0.5], ['Kreuzkümmel', 0.5]],
    ['Ofen auf 200 °C Umluft vorheizen.', 'Süßkartoffeln längs halbieren, mit Öl einreiben und 30 Min. backen.', 'Kichererbsen mit Gewürzen mischen und die letzten 15 Min. mitrösten.', 'Mit Spinat, Kichererbsen, Hummus und Zitrone anrichten.']),
  M('lachs', 'Lachs mit Ofenkartoffeln & Brokkoli', '🐟', { d: 'fisch', p: 'fisch', k: 'deutsch', t: 35, c: 3, kid: 1, rest: 0 },
    [['Lachsfilet', 125], ['Kartoffeln', 250], ['Brokkoli', 150], ['Zitrone', 0.25], ['Olivenöl', 1.5]],
    ['Ofen auf 200 °C Umluft vorheizen.', 'Kartoffeln vierteln, mit Öl und Salz mischen und 25 Min. backen.', 'Lachs salzen, pfeffern, mit Zitrone beträufeln und die letzten 12 Min. mitbacken.', 'Brokkoli 5 Min. dämpfen und dazu servieren.']),
  M('fischst', 'Fischstäbchen mit Kartoffelpüree & Erbsen', '🐠', { d: 'fisch', p: 'fisch', k: 'deutsch', t: 30, c: 1, kid: 1, rest: 0 },
    [['Fischstäbchen', 5], ['Kartoffeln', 250], ['Milch', 60], ['Butter', 15], ['Erbsen (TK)', 100], ['Muskat', 0]],
    ['Kartoffeln schälen und in Salzwasser 20 Min. weich kochen.', 'Fischstäbchen nach Packungsangabe braten oder backen.', 'Erbsen in wenig Wasser 5 Min. garen.', 'Kartoffeln mit warmer Milch und Butter stampfen, mit Salz und Muskat würzen.']),
  M('kartsuppe', 'Kartoffelsuppe mit Würstchen', '🥣', { d: 'fleisch', p: 'schwein', k: 'deutsch', t: 45, c: 1, kid: 1, rest: 1 },
    [['Kartoffeln', 250], ['Karotte', 0.5], ['Lauch', 0.33], ['Zwiebel', 0.5], ['Gemüsebrühe', 300], ['Sahne', 30], ['Wiener Würstchen', 1], ['Majoran', 0.5], ['Petersilie', 0.15], ['Rapsöl', 0.5]],
    ['Zwiebel, Kartoffeln, Karotte und Lauch klein schneiden und in Öl anschwitzen.', 'Brühe angießen und 20 Min. köcheln.', 'Teilweise pürieren, Sahne und Majoran zugeben.', 'Würstchen in Scheiben darin erwärmen, mit Petersilie servieren.']),
  M('linsen', 'Linseneintopf', '🍲', { d: 'vegan', p: 'huelsen', k: 'deutsch', t: 50, c: 1, kid: 1, rest: 1 },
    [['Tellerlinsen', 70], ['Kartoffeln', 150], ['Karotte', 0.5], ['Lauch', 0.33], ['Zwiebel', 0.5], ['Gemüsebrühe', 350], ['Tomatenmark', 1], ['Essig', 1], ['Majoran', 0.5], ['Rapsöl', 1], ['Petersilie', 0.15]],
    ['Zwiebel, Karotte und Lauch würfeln und in Öl anschwitzen, Tomatenmark mitrösten.', 'Linsen, gewürfelte Kartoffeln und Brühe zugeben, 30 Min. köcheln.', 'Mit Essig, Majoran, Salz und Pfeffer abschmecken, mit Petersilie servieren.']),
  M('kaesesp', 'Käsespätzle mit Röstzwiebeln', '🧀', { d: 'veggie', p: 'kaese', k: 'deutsch', t: 30, c: 2, kid: 1, rest: 0 },
    [['Spätzle', 200], ['Geriebener Käse', 60], ['Zwiebel', 1], ['Butter', 15], ['Romanasalat', 0.25], ['Essig', 0.5], ['Olivenöl', 1]],
    ['Zwiebeln in Ringe schneiden und in Butter langsam goldbraun rösten.', 'Spätzle erhitzen, abwechselnd mit Käse in eine Form schichten und bei 200 °C 10 Min. überbacken.', 'Röstzwiebeln darauf geben, dazu Salat mit Essig und Öl.']),
  M('schnitzel', 'Schnitzel mit Kartoffelsalat', '🥩', { d: 'fleisch', p: 'schwein', k: 'deutsch', t: 50, c: 2, kid: 1, rest: 0 },
    [['Schweineschnitzel', 150], ['Eier', 0.5], ['Mehl', 20], ['Paniermehl', 30], ['Kartoffeln', 250], ['Gurke', 0.25], ['Zwiebel', 0.25], ['Gemüsebrühe', 60], ['Essig', 1.5], ['Senf', 0.5], ['Rapsöl', 3], ['Zitrone', 0.25]],
    ['Kartoffeln in der Schale kochen, pellen und in Scheiben schneiden.', 'Mit gewürfelter Zwiebel, warmer Brühe, Essig, Senf und 1 EL Öl mischen, 20 Min. ziehen lassen, Gurke unterheben.', 'Schnitzel flach klopfen, würzen, in Mehl, verquirltem Ei und Paniermehl wenden.', 'In reichlich Öl goldbraun ausbacken und mit Zitrone servieren.']),
  M('frikadellen', 'Frikadellen mit Kartoffeln & Möhren', '🍖', { d: 'fleisch', p: 'schwein', k: 'deutsch', t: 40, c: 1, kid: 1, rest: 0 },
    [['Hackfleisch gemischt', 125], ['Eier', 0.25], ['Paniermehl', 15], ['Zwiebel', 0.25], ['Senf', 0.5], ['Kartoffeln', 250], ['Karotte', 1], ['Butter', 10], ['Rapsöl', 1], ['Petersilie', 0.1]],
    ['Kartoffeln kochen.', 'Hack mit Ei, Paniermehl, fein gewürfelter Zwiebel, Senf, Salz und Pfeffer verkneten und Frikadellen formen.', 'In Öl von jeder Seite ca. 5 Min. braten.', 'Karotten in Scheiben in Butter mit etwas Wasser 8 Min. dünsten, mit Petersilie servieren.']),
  M('paprika', 'Gefüllte Paprika in Tomatensauce', '🫑', { d: 'fleisch', p: 'schwein', k: 'deutsch', t: 60, c: 2, kid: 1, rest: 1 },
    [['Paprika', 1.5], ['Hackfleisch gemischt', 110], ['Reis', 35], ['Zwiebel', 0.5], ['Passierte Tomaten', 200], ['Geriebener Käse', 20], ['Paprikapulver', 0.5], ['Rapsöl', 0.5]],
    ['Reis halb gar kochen. Ofen auf 180 °C vorheizen.', 'Hack mit Zwiebel anbraten, mit Reis und Paprikapulver mischen.', 'Paprika aushöhlen, füllen und in eine Form mit den gewürzten Tomaten setzen.', 'Mit Käse bestreuen und 35 Min. backen.']),
  M('kuerbis', 'Kürbissuppe mit Kokos', '🎃', { d: 'vegan', p: 'gemuese', k: 'deutsch', t: 40, c: 1, kid: 1, rest: 1 },
    [['Hokkaido-Kürbis', 300], ['Kartoffeln', 100], ['Zwiebel', 0.5], ['Ingwer', 5], ['Kokosmilch', 80], ['Gemüsebrühe', 250], ['Currypulver', 0.25], ['Rapsöl', 0.5], ['Baguette', 0.33, 1]],
    ['Kürbis (mit Schale) und Kartoffeln würfeln, Zwiebel und Ingwer hacken.', 'Alles in Öl anschwitzen, Curry kurz mitrösten, Brühe angießen und 20 Min. köcheln.', 'Kokosmilch zugeben, fein pürieren und abschmecken. Mit Baguette servieren.']),
  M('tomsuppe', 'Tomatensuppe mit Käsetoast', '🥪', { d: 'veggie', p: 'kaese', k: 'amerikanisch', t: 25, c: 1, kid: 1, rest: 0 },
    [['Passierte Tomaten', 250], ['Zwiebel', 0.5], ['Gemüsebrühe', 100], ['Sahne', 30], ['Toastbrot', 2], ['Käse in Scheiben', 40], ['Butter', 10], ['Zucker', 0.25], ['Basilikum', 0.1], ['Olivenöl', 0.5]],
    ['Zwiebel in Öl anschwitzen, Tomaten und Brühe zugeben, 10 Min. köcheln.', 'Mit Sahne, Zucker, Salz und Pfeffer abschmecken, fein pürieren.', 'Toast mit Käse belegen, außen buttern und in der Pfanne goldbraun braten.', 'Suppe mit Basilikum und Käsetoast servieren.']),
  M('gnocchi', 'Gnocchi-Pfanne mit Spinat & Tomaten', '🥟', { d: 'veggie', p: 'kaese', k: 'italienisch', t: 20, c: 2, kid: 1, rest: 0 },
    [['Gnocchi', 200], ['Babyspinat', 75], ['Kirschtomaten', 100], ['Frischkäse', 40], ['Parmesan', 15, 1], ['Knoblauch', 1], ['Olivenöl', 1]],
    ['Gnocchi in Öl goldbraun braten.', 'Knoblauch und halbierte Tomaten zugeben, 2 Min. mitbraten.', 'Frischkäse mit etwas Wasser einrühren, Spinat zusammenfallen lassen.', 'Abschmecken und mit Parmesan servieren.']),
  M('lachspasta', 'Pasta mit Lachs-Sahne-Sauce', '🐟', { d: 'fisch', p: 'fisch', k: 'italienisch', t: 25, c: 3, kid: 1, rest: 0 },
    [['Penne', 125], ['Lachsfilet', 100], ['Sahne', 75], ['Babyspinat', 40], ['Zitrone', 0.25], ['Knoblauch', 1], ['Olivenöl', 0.5]],
    ['Nudeln kochen.', 'Lachs würfeln und mit Knoblauch in Öl kurz anbraten.', 'Sahne angießen, 3 Min. köcheln, Spinat unterheben.', 'Mit Zitrone, Salz und Pfeffer abschmecken und mit den Nudeln mischen.']),
  M('pesto', 'Pasta mit Brokkoli & Pesto', '🌿', { d: 'veggie', p: 'gemuese', k: 'italienisch', t: 20, c: 2, kid: 1, rest: 0 },
    [['Penne', 125], ['Brokkoli', 150], ['Pesto', 50], ['Kirschtomaten', 60], ['Parmesan', 10, 1]],
    ['Nudeln kochen, Brokkoli-Röschen die letzten 4 Min. mitkochen.', 'Abgießen, etwas Kochwasser auffangen.', 'Mit Pesto, halbierten Tomaten und einem Schluck Kochwasser mischen, mit Parmesan servieren.']),
  M('burger', 'Burger mit Ofen-Pommes', '🍔', { d: 'fleisch', p: 'rind', k: 'amerikanisch', t: 40, c: 2, kid: 1, rest: 0 },
    [['Burgerbrötchen', 1], ['Rinderhackfleisch', 150], ['Käse in Scheiben', 20, 1], ['Tomaten', 0.5], ['Romanasalat', 0.15], ['Zwiebel', 0.25], ['Gurke', 0.15], ['Ketchup', 1], ['Kartoffeln', 250], ['Rapsöl', 1.5], ['Paprikapulver', 0.25]],
    ['Kartoffeln in Stifte schneiden, mit Öl, Salz und Paprikapulver mischen, bei 220 °C 25–30 Min. backen.', 'Hack salzen, pfeffern und zu flachen Patties formen.', 'Patties 3–4 Min. pro Seite braten, kurz vor Ende mit Käse belegen.', 'Brötchen toasten und mit Salat, Tomate, Gurke, Zwiebel und Ketchup belegen.']),
  M('halloumi', 'Halloumi-Burger mit Ofen-Pommes', '🍔', { d: 'veggie', p: 'kaese', k: 'amerikanisch', t: 35, c: 3, kid: 1, rest: 0 },
    [['Burgerbrötchen', 1], ['Halloumi', 100], ['Tomaten', 0.5], ['Romanasalat', 0.15], ['Zwiebel', 0.25], ['Saure Sahne', 30], ['Kartoffeln', 250], ['Rapsöl', 1.5], ['Paprikapulver', 0.25]],
    ['Kartoffeln in Stifte schneiden, mit Öl, Salz und Paprikapulver mischen, bei 220 °C 25–30 Min. backen.', 'Halloumi in Scheiben schneiden und ohne Fett goldbraun braten.', 'Brötchen toasten, mit saurer Sahne, Salat, Tomate, Zwiebel und Halloumi belegen.']),
  M('quiche', 'Lauch-Käse-Quiche', '🥧', { d: 'veggie', p: 'ei', k: 'franzoesisch', t: 60, c: 2, kid: 0, rest: 1 },
    [['Quicheteig', 0.25], ['Lauch', 0.5], ['Eier', 1], ['Sahne', 50], ['Geriebener Käse', 30], ['Butter', 5], ['Muskat', 0]],
    ['Ofen auf 190 °C vorheizen, Teig in eine Form legen.', 'Lauch in Ringe schneiden und in Butter 5 Min. dünsten.', 'Eier, Sahne und Käse verquirlen, mit Salz, Pfeffer und Muskat würzen.', 'Lauch auf den Teig geben, Guss darüber gießen und 35 Min. backen.']),
  M('flammkuchen', 'Flammkuchen Elsässer Art', '🥓', { d: 'fleisch', p: 'schwein', k: 'franzoesisch', t: 25, c: 1, kid: 1, rest: 0 },
    [['Flammkuchenteig', 0.5], ['Schmand', 60], ['Speckwürfel', 40], ['Zwiebel', 0.5], ['Muskat', 0]],
    ['Ofen auf 250 °C vorheizen.', 'Teig ausrollen und mit gewürztem Schmand bestreichen.', 'Mit Zwiebelringen und Speck belegen.', '10–12 Min. knusprig backen.']),
  M('kraeuterquark', 'Ofenkartoffeln mit Kräuterquark', '🥔', { d: 'veggie', p: 'milch', k: 'deutsch', t: 50, c: 1, kid: 1, rest: 0 },
    [['Kartoffeln', 350], ['Quark', 125], ['Milch', 20], ['Schnittlauch', 0.25], ['Knoblauch', 0.5], ['Gurke', 0.25], ['Olivenöl', 1]],
    ['Kartoffeln halbieren, mit Öl und Salz auf ein Blech legen und bei 200 °C 40 Min. backen.', 'Quark mit Milch glatt rühren, Schnittlauch, Knoblauch und fein gewürfelte Gurke unterrühren, würzen.', 'Kartoffeln mit dem Quark servieren.']),
  M('pfannkuchen', 'Pfannkuchen mit Apfelmus', '🥞', { d: 'veggie', p: 'ei', k: 'deutsch', t: 25, c: 1, kid: 1, rest: 0 },
    [['Mehl', 70], ['Milch', 140], ['Eier', 1], ['Apfelmus', 120], ['Butter', 10], ['Zucker', 0.5], ['Zimt', 0.25]],
    ['Mehl, Milch, Eier, Zucker und eine Prise Salz zu einem glatten Teig verrühren, 10 Min. quellen lassen.', 'Portionsweise in Butter dünne Pfannkuchen ausbacken.', 'Mit Apfelmus und Zimt servieren.']),
  M('bratkart', 'Bratkartoffeln mit Spiegelei & Salat', '🍳', { d: 'veggie', p: 'ei', k: 'deutsch', t: 35, c: 1, kid: 1, rest: 0 },
    [['Kartoffeln', 250], ['Eier', 2], ['Zwiebel', 0.5], ['Romanasalat', 0.25], ['Schnittlauch', 0.1], ['Rapsöl', 1.5], ['Essig', 0.5], ['Senf', 0.25]],
    ['Kartoffeln kochen (gerne schon am Vortag), abkühlen lassen und in Scheiben schneiden.', 'In Öl knusprig braten, Zwiebelwürfel zugeben, salzen und pfeffern.', 'Spiegeleier braten.', 'Salat mit Essig, Senf und Öl anmachen, alles mit Schnittlauch servieren.']),
  M('zucchpuffer', 'Zucchini-Puffer mit Joghurt-Dip', '🥒', { d: 'veggie', p: 'ei', k: 'mediterran', t: 30, c: 1, kid: 1, rest: 0 },
    [['Zucchini', 1], ['Eier', 0.5], ['Mehl', 30], ['Geriebener Käse', 20], ['Naturjoghurt', 80], ['Knoblauch', 0.5], ['Rapsöl', 1.5], ['Baguette', 0.25, 1]],
    ['Zucchini grob raspeln, salzen, 10 Min. ziehen lassen und gut ausdrücken.', 'Mit Ei, Mehl und Käse mischen, pfeffern.', 'Kleine Puffer in Öl von beiden Seiten goldbraun braten.', 'Joghurt mit Knoblauch und Salz verrühren und dazu reichen.']),
  M('gulasch', 'Rindergulasch mit Bandnudeln', '🍲', { d: 'fleisch', p: 'rind', k: 'deutsch', t: 120, c: 3, kid: 1, rest: 1 },
    [['Rindergulasch', 175], ['Zwiebel', 1], ['Paprika', 0.5], ['Tomatenmark', 1], ['Paprikapulver', 1.5], ['Gemüsebrühe', 200], ['Bandnudeln', 100], ['Rapsöl', 1], ['Majoran', 0.25], ['Speisestärke', 0.5]],
    ['Fleisch portionsweise in Öl scharf anbraten.', 'Zwiebeln zugeben und goldbraun rösten, Tomatenmark und Paprikapulver kurz mitrösten.', 'Mit Brühe ablöschen, Majoran zugeben und zugedeckt ca. 90 Min. schmoren. Paprika die letzten 20 Min. mitgaren.', 'Sauce bei Bedarf mit Stärke binden, mit Bandnudeln servieren.']),

  // Frühstück
  B('porridge', 'Porridge mit Banane & Zimt', '🥣', { d: 'veggie', t: 10, c: 1, kid: 1 },
    [['Haferflocken', 50], ['Milch', 200], ['Banane', 0.5], ['Zimt', 0.25], ['Honig', 0.5]],
    ['Haferflocken mit Milch und einer Prise Salz aufkochen und 3–5 Min. unter Rühren quellen lassen.', 'Mit Bananenscheiben, Zimt und Honig servieren.']),
  B('muesli', 'Müsli mit Joghurt & Beeren', '🫐', { d: 'veggie', t: 5, c: 1, kid: 1 },
    [['Müsli', 60], ['Naturjoghurt', 150], ['Beeren (TK)', 60]],
    ['Beeren am Vorabend im Kühlschrank auftauen lassen.', 'Joghurt mit Müsli und Beeren anrichten.']),
  B('kaesebrot', 'Vollkornbrot mit Käse & Gurke', '🧀', { d: 'veggie', t: 5, c: 1, kid: 1 },
    [['Vollkornbrot', 2], ['Butter', 10], ['Käse in Scheiben', 40], ['Gurke', 0.2]],
    ['Brot buttern, mit Käse und Gurkenscheiben belegen.']),
  B('ruehrei', 'Rührei mit Toast', '🍳', { d: 'veggie', t: 10, c: 1, kid: 1 },
    [['Eier', 2], ['Milch', 20], ['Toastbrot', 2], ['Butter', 10], ['Schnittlauch', 0.1]],
    ['Eier mit Milch, Salz und Pfeffer verquirlen.', 'In Butter bei mittlerer Hitze langsam stocken lassen.', 'Mit getoastetem Brot und Schnittlauch servieren.']),
  B('broetchen', 'Brötchen mit Frischkäse & Marmelade', '🥐', { d: 'veggie', t: 5, c: 1, kid: 1 },
    [['Brötchen', 2], ['Frischkäse', 30], ['Marmelade', 25], ['Butter', 10]],
    ['Brötchen aufbacken und nach Lust und Laune bestreichen.']),
  B('oats', 'Overnight Oats mit Apfel', '🍎', { d: 'vegan', t: 5, c: 1, kid: 1 },
    [['Haferflocken', 50], ['Haferdrink', 150], ['Apfel', 0.5], ['Zimt', 0.25], ['Ahornsirup', 0.5]],
    ['Am Vorabend Haferflocken mit Haferdrink und Zimt mischen und abgedeckt in den Kühlschrank stellen.', 'Morgens mit geriebenem Apfel und Ahornsirup servieren.']),
  B('avocado', 'Avocado-Brot mit Tomate', '🥑', { d: 'vegan', t: 10, c: 2, kid: 0 },
    [['Vollkornbrot', 2], ['Avocado', 0.5], ['Tomaten', 0.5], ['Zitrone', 0.15]],
    ['Avocado mit Zitronensaft, Salz und Pfeffer zerdrücken.', 'Auf getoastetes Brot streichen und mit Tomatenscheiben belegen.']),
  B('hummusbrot', 'Hummus-Brot mit Gurke', '🥒', { d: 'vegan', t: 5, c: 1, kid: 0 },
    [['Vollkornbrot', 2], ['Hummus', 40], ['Gurke', 0.25], ['Tomaten', 0.5]],
    ['Brot mit Hummus bestreichen und mit Gurke und Tomate belegen.']),
  B('quark', 'Quark mit Banane & Walnüssen', '🍌', { d: 'veggie', t: 5, c: 1, kid: 0 },
    [['Quark', 125], ['Milch', 30], ['Banane', 0.5], ['Walnüsse', 15], ['Honig', 1]],
    ['Quark mit Milch cremig rühren.', 'Mit Banane, gehackten Walnüssen und Honig servieren.']),
  B('obstbowl', 'Joghurt-Obst-Bowl', '🍓', { d: 'veggie', t: 5, c: 1, kid: 1 },
    [['Naturjoghurt', 150], ['Apfel', 0.5], ['Banane', 0.5], ['Haferflocken', 25], ['Honig', 0.5]],
    ['Obst klein schneiden.', 'Mit Joghurt, Haferflocken und Honig in einer Schale anrichten.']),
  B('muesliveg', 'Müsli mit Haferdrink & Banane', '🥛', { d: 'vegan', t: 5, c: 1, kid: 1 },
    [['Müsli', 60], ['Haferdrink', 150], ['Banane', 0.5]],
    ['Müsli mit Haferdrink übergießen und mit Bananenscheiben servieren.']),
  B('pancakes', 'Fluffige Pancakes mit Beeren', '🥞', { d: 'veggie', t: 25, c: 1, kid: 1 },
    [['Mehl', 60], ['Milch', 80], ['Eier', 1], ['Zucker', 0.5], ['Backpulver', 0.5], ['Butter', 5], ['Beeren (TK)', 60], ['Ahornsirup', 1]],
    ['Mehl, Backpulver, Zucker, Milch und Ei glatt rühren.', 'Kleine Pancakes in wenig Butter von beiden Seiten goldbraun backen.', 'Mit Beeren und Ahornsirup servieren.']),
];
